SEED: 100
MODEL:
    ARCH: cifar_resnet18
    INPUTSHAPE: [32, 32]
TRAIN:
    EPOCHS: 400
    USE_DDP: True
    SYNC_BN: False
    DATASET: cifar10
    BATCH_SIZE: 128 # per-gpu
    PRINT_FREQ: 10
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0005 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.05 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
SSL:
    TYPE: SimSiam
    SETTING:
        DIM: 2048
        HIDDEN_DIM: 2048
